language: c
compiler:
  - gcc

before_install:
  - sudo apt-get -q update
  - sudo apt-get -q install liblo-dev libudev-dev libconfuse-dev libavahi-compat-libdnssd-dev
  - git clone git://github.com/monome/libmonome.git
  - cd libmonome && ./waf configure && ./waf && sudo ./waf install; cd ..

script: ./waf configure && ./waf
